name: Test Use Cases - TT02

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  test-staging:
    name: Run use case tests on staging
    uses: ./.github/workflows/test-use-cases.yml
    with:
      environment: use-case-staging
    secrets: inherit

  test-staging-legacy:
    name: Run legacy use case tests on staging
    uses: ./.github/workflows/test-use-cases-legacy.yml
    with:
      environment: use-case-staging
    secrets: inherit
