name: Test Use Cases - PROD

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  test-prod:
    name: Run use case tests on production
    uses: ./.github/workflows/test-use-cases.yml
    with:
      environment: use-case-production
    secrets: inherit

  test-prod-legacy:
    name: Run legacy use case tests on prod
    uses: ./.github/workflows/test-use-cases-legacy.yml
    with:
      environment: use-case-production
    secrets: inherit